### ISSUE TITLE
Input line numbers not shown

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/WolframLanguageForJupyter#14] opened 2019-05-18 09:22 UTC
The input line numbers are not shown. I only see `In[*]` instead of `In[123]`. The `*` is confusing because it looks as if the cell were still evaluating.

Also, `$Line` does not increment as expected.

![image](https://user-images.githubusercontent.com/1212871/57967434-3b953900-795f-11e9-920f-315977f91e54.png)

**Comment by cc-wr** [comment] 2019-05-19 22:12
I cannot reproduce the problem of `In[*]` not resolving to an input number, but it is a known issue for an earlier version of the project.

Are you using the latest version on GitHub? If you are not, does the issue persist if you update and reinstall?

The `$Line` issue will be fixed with an update to the GitHub repository from a pull request internal to Wolfram Research.

**Comment by cc-wr** [comment] 2019-05-21 12:47
Did 3466d98152aab8143e1384a67de117fb3866b123 fix the problem with `In[*]`?

**Comment by szhorvat** [comment] 2019-05-21 12:59
No, that it did not fix. But `%` works now.

However, the values assigned to `In` look a bit funny. It's not clear if this was intentional.

![image](https://user-images.githubusercontent.com/1212871/58098075-11e74680-7bd9-11e9-90de-74ec38b56c4b.png)

**Comment by cc-wr** [comment] 2019-05-21 13:06
Yes, that is intentional.

---

This issue is another that I cannot explicitly reproduce.

Is anything significant output by the console during this that may seem relevant?

**Comment by szhorvat** [comment] 2019-05-21 13:47
No, I do not see anything relevant in the terminal. Let's go through our setup in detail.

I have

 - Mathematica 12.0.0 final version on macOS 10.14.5.
 - `jupyter --version` says 4.4.0
 - I use it with `jupyter lab`
 - Chrome as the browser
 - I used the code from this repository and I attempted to start with a clean Jupyter configuration. I removed all previous Wolfram kernels before adding this one, and then verified that it is launched the Mathematica version I expect, and that it is loading the WolframLanguageForJupyter script I expect (I do this by looking at the open `Streams[]`)

**Comment by szhorvat** [comment] 2019-05-21 13:49
Writing that down made me realize that one can also start it with `jupyter notebook`. If I do that, I do see the input line numbers. Did we find the culprit?

**Comment by cc-wr** [comment] 2019-05-21 14:15
Yeah, I usually just use `jupyter notebook`.

So is it only when the Jupyter notebook is started by JupyterLab that the input line numbers do not resolve for you?

Does starting with `jupyter notebook` affect #15 at all?

**Comment by szhorvat** [comment] 2019-05-21 14:19
> So is it only when the Jupyter notebook is started by JupyterLab that the input line numbers do not resolve for you?

Yes.

> Does starting with jupyter notebook affect #15 at all?

It didn't stop working _yet_ ... Let's give it half an hour.

**Comment by cc-wr** [comment] 2019-05-21 15:13
Ok, so the short-term solution for this problem is to just use the `jupyter notebook` invocation.

I have created a new issue for the problems that occur when `WolframLanguageForJupyter` is launched, indirectly, from JupyterLab. See #32.

**Closed by cc-wr** 2019-05-21 15:13 UTC
Labels: fix incoming

**Comment by arnoudbuzing** [comment] 2019-05-21 15:21
Besides `jupyter notebook` what other ways are there to launch Jupyter? (I didn't even realize there were other ways...)

**Comment by cc-wr** [comment] 2019-05-21 18:08
This `$Line` issue should now be fixed in master.
