### ISSUE TITLE
Install script hangs under Linux

### ISSUE THREAD

**Issue by fedeinthemix** [WolframResearch/WolframLanguageForJupyter#34] opened 2019-05-22 16:15 UTC
I'm using Debian 9 which provides jupyter 4.2.1. I've installed the "Free Wolfram Engine for Developers" in the default paths and activated it. On the console it works as expected.

I've tried to install WolframLanguageForJupyter with the command
```
./configure-jupyter.wls add /opt/Wolfram/WolframScript/bin/wolframscript
```
I get the error message "Combination of options is not valid" and it hangs indefinitely.

I also tried 
```
./configure-jupyter.wls add /usr/local/Wolfram/WolframEngine/12.0/Executables/wolfram
```
and in this case I get the error message "configure-jupyter.wls: Communication with provided Wolfram Engine binary could not be established." and the script exits.

**Comment by szhorvat** [comment] 2019-05-22 16:38
Are you able to run `wolframscript` on its own and get a working REPL?

**Comment by fedeinthemix** [comment] 2019-05-22 19:58
Yes, 'wolframscript' runs flawlessly by itself.

**Comment by cc-wr** [comment] 2019-05-23 00:15
I can reproduce on Debian 9 and Jupyter 4.2.1.

**Comment by cc-wr** [comment] 2019-05-23 10:14
On another look, I actually cannot reproduce the second problem.

---

The error message for the first problem occurs because internally, this project uses `LinkLaunch` to communicate with Wolfram Research binaries. This command generates arguments that confuse `wolframscript`. (Namely, `LinkLaunch` generates `-link*`-type arguments which `wolframscript` expects to be its own `-l` / `--local` arguments.)

**Comment by fedeinthemix** [comment] 2019-05-23 15:59
I tried again after rebooting the machine and with the second command it now works for me as well.
I've created a notebook and it does work. I'm not sure what happened yesterday.

Thanks for your help!

It would maybe be useful to point out in the installation script not to use `wolframscript`, but instead to use the `wolfram` executable.

**Comment by cc-wr** [comment] 2019-05-23 18:48
You may also want to check out this branch that adds support for adding `wolframscript`, if it is decided that is something that should be supported: [feature/support-wolframscript-as-wolframengineeinaries](https://github.com/WolframResearch/WolframLanguageForJupyter/tree/feature/support-wolframscript-as-wolframengineeinaries).

**Comment by cc-wr** [comment] 2019-05-23 19:02
> It would maybe be useful to point out in the installation script not to use `wolframscript`, but instead to use the `wolfram` executable.

Please see the pull request #36.

**Comment by cc-wr** [comment] 2019-05-23 19:03
I will close this issue for the moment, but please feel free to update it further with any comments/issues/concerns.

**Closed by cc-wr** 2019-05-23 19:03 UTC
Labels: bug
