### ISSUE TITLE
Print[] does not use OutputForm, and it does not even handle an explicit OutputForm

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/WolframLanguageForJupyter#17] opened 2019-05-18 09:36 UTC
`Print` should be using `OutputForm` by default. It should not show the internal structure of certain expressions.

![image](https://user-images.githubusercontent.com/1212871/57967556-1275a800-7961-11e9-9eb4-0e4f5e2f11c6.png)

Furthermore, `Print@OutputForm[something]` does not behave correctly. It does not format in OutputForm, and retains a visible OutputForm wrapper.

![image](https://user-images.githubusercontent.com/1212871/57967571-2d481c80-7961-11e9-81a1-0a0d9b6369f7.png)

Compare the friendlier behaviour of the terminal interface:

![image](https://user-images.githubusercontent.com/1212871/57967578-3933de80-7961-11e9-9e2a-21b799a45acc.png)

**Comment by cc-wr** [comment] 2019-05-19 21:59
I cannot reproduce this issue.

Are you using the latest version on GitHub? If you are not, is the issue resolved if you update and reinstall?

**Comment by szhorvat** [comment] 2019-05-20 07:59
I am pretty sure that I was using the latest version on GitHub, but just in case:

 - I removed the kernelspec directly
 - I removed `~/.jupyter` to reset the configuration
 - I double-checked that I have the latest version of the repo locally and re-installed using `./configure-jupyter.wls add`

All the issues that you say should be fixed are still there.

Is there any way I can check which version I am running, directly from a Jupyter notebook?

As a hackish way, I looked at `Streams[]` in hope of finding an open file that would reveal what is actually running.  It does look like the running version is exactly the one I expect it to be:

![image](https://user-images.githubusercontent.com/1212871/58005392-dddf2900-7ae5-11e9-8aaa-9c86d47daeab.png)

Can you double-check that you have the latest version on GitHub?  Last commit was on March 19, b70e8f5

**Comment by szhorvat** [comment] 2019-05-20 08:01
I am going to delete this comment in a few minutes due to the prerelease agreement, but you should get the email nevertheless. I am using the "Wolfram Engine for Developers". I don't think this should make a difference though. You could join Arnoud's developer chat to discuss further ...

**Comment by cc-wr** [comment] 2019-05-21 11:20
This is a problem specific to certain versions of the Wolfram Kernel.

I will add a fix.

**Comment by cc-wr** [comment] 2019-05-21 18:10
This issue should now be fixed in master.

**Closed by cc-wr** 2019-05-21 18:10 UTC
