### ISSUE TITLE
configure-jupyter.wls: Communication with provided Wolfram Engine binary could not be established.

### ISSUE THREAD

**Issue by shirha** [WolframResearch/WolframLanguageForJupyter#85] opened 2020-04-13 03:21 UTC
Wolfram Engine 12
Windows 10

when I run the configure-jupyter.wls script

`PS D:\apps\Mathematica\WolframLanguageForJupyter> wolframscript configure-jupyter.wls add "C:\Program Files\Wolfram Research\Wolfram Engine\12.0\WolframKernel.exe" "C:\Anaconda3\Scripts\Jupyter.exe"`

 I get the the following message

`configure-jupyter.wls: Communication with provided Wolfram Engine binary could not be established.`

I get the same message if I use Wolfram.exe instead of WolframKernel.exe
Please help.

**Comment by cc-wr** [comment] 2020-06-23 05:11
@shirha,

(I apologize for the delay.)

Unfortunately, I am unable to reproduce this issue.

Can you verify that `C:\Program Files\Wolfram Research\Wolfram Engine\12.0\wolfram.exe` can run on its own? (It may be possible that `wolframscript` is using a different Wolfram Engine.)

Also, are there any additional details of your environment that you can share?

**Comment by cc-wr** [comment] 2020-12-08 10:02
I am closing this issue because additional diagnostic information was not provided.

**Closed by cc-wr** 2020-12-08 10:02 UTC
Labels: on hold
